In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Ads.csv")

In [3]:
dataset

Age  EstimatedSalary  Purchased
0     21            19290          0
1     35            20290          0
2     26            43290          0
3     27            57290          0
4     19            76290          0
..   ...              ...        ...
395   46            41290          1
396   51            23290          1
397   50            20290          1
398   36            33290          0
399   49            36290          1

[400 rows x 3 columns]

## Step 3- Creating Feature matrix(x) and DVV(y)

In [4]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [5]:
x

array([[    21,  19290],
       [    35,  20290],
       [    26,  43290],
       [    27,  57290],
       [    19,  76290],
       [    27,  58290],
       [    27,  84290],
       [    32, 150290],
       [    25,  33290],
       [    35,  65290],
       [    26,  80290],
       [    26,  52290],
       [    20,  86290],
       [    32,  18290],
       [    18,  82290],
       [    29,  80290],
       [    47,  25290],
       [    45,  26290],
       [    46,  28290],
       [    48,  29290],
       [    45,  22290],
       [    47,  49290],
       [    48,  41290],
       [    45,  22290],
       [    46,  23290],
       [    47,  20290],
       [    49,  28290],
       [    47,  30290],
       [    29,  43290],
       [    31,  18290],
       [    31,  74290],
       [    27, 137290],
       [    21,  16290],
       [    28,  44290],
       [    27,  90290],
       [    35,  27290],
       [    33,  28290],
       [    30,  49290],
       [    26,  72290],
       [    27,  31290],


In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

## Step 4: Replace missing values

In [7]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,:])
x[:,:]=imputer.transform(x[:,:])

## Step 5: Encoding(Not requiredsince no caegorical data)

## Step 6: Splitting dataset into training and testing dataset

In [8]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [9]:
xtrain

array([[    29,  28290],
       [    45,  22290],
       [    46, 117290],
       [    32,  18290],
       [    22,  81290],
       [    25,  87290],
       [    48,  33290],
       [    35,  58290],
       [    47,  23290],
       [    26,  32290],
       [    32, 135290],
       [    60,  34290],
       [    52,  21290],
       [    38,  55290],
       [    25,  90290],
       [    58,  38290],
       [    49,  88290],
       [    37,  78290],
       [    35,  77290],
       [    34,  43290],
       [    20,  49290],
       [    46,  88290],
       [    31,  34290],
       [    47,  30290],
       [    35,  50290],
       [    39,  96290],
       [    33, 113290],
       [    49,  86290],
       [    45,  79290],
       [    44,  39290],
       [    41,  59290],
       [    42,  53290],
       [    35,  73290],
       [    41,  72290],
       [    27,  96290],
       [    30, 116290],
       [    41,  52290],
       [    41,  52290],
       [    20,  82290],
       [    46,  41290],


In [10]:
ytrain

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,

In [11]:
xtest

array([[    36,  33290],
       [    39,  61290],
       [    36, 118290],
       [    39, 122290],
       [    26, 118290],
       [    38,  65290],
       [    20,  36290],
       [    49,  89290],
       [    31,  18290],
       [    48, 141290],
       [    34,  72290],
       [    39,  73290],
       [    35,  72290],
       [    48, 131290],
       [    53,  82290],
       [    56, 133290],
       [    60,  83290],
       [    27,  58290],
       [    28,  87290],
       [    60, 102290],
       [    40,  75290],
       [    50,  88290],
       [    44, 139290],
       [    47,  43290],
       [    45,  26290],
       [    26,  15290],
       [    58,  47290],
       [    49,  74290],
       [    53,  34290],
       [    52, 114290],
       [    39,  42290],
       [    19,  76290],
       [    18,  86290],
       [    57,  74290],
       [    27,  84290],
       [    30,  80290],
       [    22,  18290],
       [    32,  86290],
       [    50,  20290],
       [    19,  25290],


In [12]:
ytest

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

## Step 7:Feature scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain[:,:]=sc.fit_transform(xtrain[:, :])
xtest[:,:]=sc.fit_transform(xtest[:, :])

# Step B- Classification model using Naive Bayes algo

## Step 1: Training the classification model

In [14]:
from sklearn.naive_bayes import GaussianNB
NB=GaussianNB()             
NB.fit(xtrain,ytrain)

GaussianNB()

In [15]:
yestimated=NB.predict(xtest)
print(np.concatenate((yestimated.reshape(len(yestimated),1),ytest.reshape(len(ytest),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score, mean_squared_error
cm=confusion_matrix(ytest, yestimated) 
print('confusion matrix')
print(cm)
print('accuracy=', accuracy_score(ytest,yestimated)) 
print('precision=', precision_score(ytest,yestimated)) 
print('MSE=',mean_squared_error(ytest,yestimated))

confusion matrix
[[42  6]
 [ 9 23]]
accuracy= 0.8125
precision= 0.7931034482758621
MSE= 0.1875
